name = "QSMCTemplate"
version = "1.0.0"
author = "<your name>"
description = "Template modpack, structure based on Dimension-Gateway."
pack_format = 3

[versions]
forge="47.4.10"
minecraft="1.20.1"